[package]
name = "medea"
authors = ["Thomas Bollmeier"]
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
colored = "3.1.1"

[dependencies.clap]
version = "4"
features = ["derive", "cargo", "string"]