[project]
name = "medea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alteraparser",
    "pytest>=9.0.2",
]

[tool.uv.sources]
alteraparser = { path = "deps/alteraparser-2.0.6-py3-none-any.whl" }
